gitSourceBranch = "main"
changelog = false
classOrder = []

[[classOrder]]
classes = ["Repl"]

[[classOrder]]
section = "Server"
classes = ["ServerRepl", "RemoteSignal", "RemoteProperty"]

[[classOrder]]
section = "Client"
classes = ["ClientRepl", "ClientRemoteSignal", "ClientRemoteProperty"]

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
url = "https://nottirb.com"
tagline = "Replication library for Roblox"